var someColors="           ".split(" ");$(document).ready(function(){});
$(document).ready(function(){$(".share-btns-custom").each(function(){var a,c,b;a=0<$(this).parent().parent(".post").find(".post-title").length?$(this).parent().parent(".post").find(".post-title").text().trim():document.title;c=0<$(this).parent().parent(".post").find(".post-title").children("a").length?$(this).parent().parent(".post").find(".post-title").children("a").attr("href"):$("link[rel=canonical]").attr("href")?$("link[rel=canonical]").attr("href"):window.location.href;0<$(this).parent().parent(".post").find(".image-thumbnail a img").length?
b=$(this).parent().parent(".post").find(".image-thumbnail a img").attr("src"):$(this).parent().parent(".post").find(".post-body").find("img")?(b=$(this).parent().parent(".post").find(".post-body").find("img"),b=$(b[0]).attr("src")):b=void 0;var e="http://www.facebook.com/share.php?u="+c+"&title="+encodeURIComponent(a)+"",f="http://twitter.com/home?status="+encodeURIComponent(a)+"+"+c+"",g="https://plus.google.com/share?url="+c+"";a="http://pinterest.com/pin/create/bookmarklet/?media="+b+"&url="+c+
"&is_video=false&description="+encodeURIComponent(a)+"";console.log(e);$(this).find(".sc-pill.fb-pill a").attr("href",e);$(this).find(".sc-pill.tw-pill a").attr("href",f);$(this).find(".sc-pill.gp-pill a").attr("href",g);$(this).find(".sc-pill.pn-pill a").attr("href",a)});$(".share-btns-custom .sc-pill a").on("click",function(a){var c=Math.round(($(this).offset().top-window.pageYOffset)/2),b=Math.round(($(this).offset().left-window.pageXOffset)/2);window.open($(this).attr("href"),"_blank","toolbar=yes, scrollbars=yes, resizable=yes, top="+
c+", left="+b+", width=600, height=380");a.preventDefault()});if(void 0!==QueryString.q){var a=urlplustoplus(QueryString.q);$(".search-query-input").val(a);a='<form class="search-box" action="/search" id="search_in_page" method="get"><input class="search-query-input" name="q" placeholder="Search the blog.." value="'+a+'" type="text"><button type="submit" class="submit-btn-form">Search</button></form>';$(".status-msg-wrap").before(a);$(".post")}});
$(function(){$("a[href*=#]:not([href=#])").click(function(){if(location.pathname.replace(/^\//,"")==this.pathname.replace(/^\//,"")&&location.hostname==this.hostname){var a=$(this.hash),a=a.length?a:$("[name="+this.hash.slice(1)+"]");if(a.length)return $("html,body").animate({scrollTop:a.offset().top},1E3),!1}})});function randInt(a,d){return Math.floor(Math.random()*(d-a+1))+a}Object.size=function(a){var d=0,c;for(c in a)a.hasOwnProperty(c)&&d++;return d};
var QueryString=function(){for(var a={},d=window.location.search.substring(1).split("&"),c=0;c<d.length;c++){var b=d[c].split("=");"undefined"===typeof a[b[0]]?a[b[0]]=b[1]:"string"===typeof a[b[0]]?a[b[0]]=[a[b[0]],b[1]]:a[b[0]].push(b[1])}return a}();function urlplustoplus(a){a=a.replace("+"," ");return a=decodeURIComponent(a)};


var _postId=$('meta[itemprop="postId"]').attr("content").trim(),_labels=[],numberOfLinks=6,related_posts={},__n=0;$(".entry-label").each(function(a){_labels.push($(this).text().trim())});var forEachLabel=0,forEachLabel=3<=_labels.length?numberOfLinks/3:numberOfLinks/_labels.length;$.ajax({url:"http://rempixels.blogspot.com/feeds/posts/summary?max-results=20&alt=json",dataType:"jsonp",success:function(a){getRelatedPosts(a)}});
function outputRelatedPosts(a,c){for(var d="",b=0;b<Object.size(related_posts);b++)d+="<li class='related-post-item'><a href='"+related_posts[b].url+"' title='"+related_posts[b].title+"'>"+related_posts[b].title+"</a></li>";$(c).html(d)}
function getRelatedPosts(a){var c=0,d=a.feed.entry.length;if(d>numberOfLinks)for(i=0;i<numberOfLinks;i++){if(d=randInt(1,_labels.length)-1,postHasLabel(a.feed.entry[i]),_labels[d]){var b=a.feed.entry[i].id.$t.split("-"),b=b[b.length-1];b!==_postId&&(related_posts[c]=relatedPostObject(a.feed.entry[i]),c+=1)}}else if(d<numberOfLinks)for(i=0;i<d;i++)b=a.feed.entry[i].id.$t.split("-"),b=b[b.length-1],b!==_postId&&(related_posts[c]=relatedPostObject(a.feed.entry[i]),c+=1);$("#relatedPost01").parent(".related-posts-container").fadeIn();
outputRelatedPosts(related_posts,"#relatedPost01")}function postHasLabel(a,c){for(var d=0;d<a.category.length;d++)if(a.category[d].term==c)return!0;return!1}function relatedPostObject(a){var c="not-available";void 0!==a.media$thumbnail&&(c=a.media$thumbnail.url);return{title:a.title.$t,summary:a.summary.$t,url:a.link[4].href,thumbnail:c}};